spring:
  application:
    name: system-gateway # Spring 应用名
  profiles:
    active: @profile.active@ # Spring 环境配置
  cloud:
    nacos:
      discovery:
        server-addr: @nacos.address@ # Nacos 服务器地址
        service: ${spring.application.name} # 注册到 Nacos 的服务名。默认值为 ${spring.application.name}。