spring:
  application:
    name: system-gateway # Spring 应用名
  profiles:
    active: dev # Spring 环境配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址

server:
  port: 10001